### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined on `soli graph`

### ISSUE THREAD

**Issue by makoto** [federicobond/soli#1]
Hi, Federico.

Great work!

`soli describe` worked like a charm but having problem with `soli graph`.

```
$ soli graph contracts/Conference.sol 
/usr/local/lib/node_modules/soli/node_modules/yargs/yargs.js:1101
      else throw err
           ^

TypeError: Cannot read property 'length' of undefined
    at _linearize (/usr/local/lib/node_modules/soli/node_modules/c3-linearization/index.js:45:19)
    at graph.(anonymous function).map.x (/usr/local/lib/node_modules/soli/node_modules/c3-linearization/index.js:52:15)
    at Array.map (<anonymous>)
    at _linearize (/usr/local/lib/node_modules/soli/node_modules/c3-linearization/index.js:52:6)
    at linearize (/usr/local/lib/node_modules/soli/node_modules/c3-linearization/index.js:65:5)
    at _loop (/usr/local/lib/node_modules/soli/lib/graph.js:101:20)
    at graph (/usr/local/lib/node_modules/soli/lib/graph.js:139:7)
    at Object.require.usage.command.command [as handler] (/usr/local/lib/node_modules/soli/bin/soli:23:5)
    at Object.runCommand (/usr/local/lib/node_modules/soli/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/soli/node_modules/yargs/yargs.js:1014:30)
$ node -v
v8.9.4
$ npm -v
5.6.0
```

OS is OSX High Sierra

**Comment by federicobond** [comment]
Great, thanks for the report! Are the input contracts open-source by any chance? Or can you provide a minimal example?

**Comment by federicobond** [comment]
@makoto can you try latest master?

**Comment by makoto** [comment]
Tried and looks good 👍

**Comment by federicobond** [comment]
Closing. Thank you!
